# Generated by Django 3.2.16 on 2023-02-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='color',
        ),
    ]
