# Generated by Django 3.2.16 on 2023-02-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_car_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
