# Generated by Django 3.2.16 on 2023-02-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='booked',
            field=models.BooleanField(),
        ),
    ]
